apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-last-name-deployment
  labels:
    app: microservice-last-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-last-name
  template:
    metadata:
      labels:
        app: microservice-last-name
    spec:
      containers:
      - name: microservice-last-name
        image: guycarmy/microservice-last-name:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /_alive
            port: 8091
        readinessProbe:
          httpGet:
            path: /_ready
            port: 8091
