apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-first-name-deployment
  labels:
    app.kubernetes.io/name: microservice-first-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice-first-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice-first-name
    spec:
      containers:
      - name: microservice-first-name
        image: guycarmy/microservice-first-name:latest
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /_alive
            port: 8090
        readinessProbe:
          httpGet:
            path: /_ready
            port: 8090
